#version: "2"
services: 
  mongo5:
    image: mongo:4.0.4
    container_name: mongo5
    restart: always
    volumes:
      - ./db/mongod.conf:/etc/mongod.conf
      - ./logs:/var/log/mongod/
      - ./db/date/:/var/lib/mongodb/
      - ./db/data/:/data/mongod/
      #- ./mongod.service:/lib/systemd/system/mongod.service
    ports:
      - "27017:27017"

  app5:
    container_name: app5
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo5
    environment: 
      - DB_HOST=mongodb://mongo5:27017/posts
    depends_on:
      - mongo5
    # command: node /usr/local/app/seeds/seed.js

